variables:
- group: ServiceConnections
- name: azureSubscription
  value: $(ServiceConnectionPRD1)
- name: docker.imageName
  value: 'submissionchecksplitter'
- name: acr.azureContainerRegistryName
  value: 'prdrwdinfac1401'
- name: acr.repositoryName
  value: 'submissionchecksplitterrepository'
- name: serviceName
  value: 'prdrwdwebfa1403'
