variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'submissionchecksplitter'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'submissionchecksplitterrepository'
  serviceName: 'prdrwdwebfa1403'
